### ISSUE TITLE
no-unregistered-classes should ignore component layer classes

### ISSUE THREAD

**Issue by Soundvessel** [schoero/eslint-plugin-better-tailwindcss#106]
Tailwind 4 has a components layer for creating custom component classes so they can be overridden by utilities later in markup.
https://tailwindcss.com/docs/adding-custom-styles#adding-component-classes

For example, I used this layer to implement a class for Material Symbol icons.

```css
@layer components {
  .material-symbols-rounded {
    @apply icon-size-md;
    speak-as: none;
  }
}
```

It would be nice if these were automatically ignored. Current workaround is to use an eslint comment or add to the igonre list where I would rather the Tailwind code be the source of truth.
